apiVersion: apps/v1
kind: Deployment
metadata:
  name: keda-pubsub-worker
  namespace: keda-pubsub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keda-pubsub-worker
  template:
    metadata:
      labels:
        app: keda-pubsub-worker
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: pubsub-secret
      containers:
      - name: worker
        image: gcr.io/gxlb-asm-01/keda-pubsub-test-worker
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        env:
        - name: PROJECT
          valueFrom:
            secretKeyRef:
              name: pubsub-secret
              key: PROJECT
        - name: PUBSUB_INGEST_SUBSCRIPTION
          value: ingest-subscription
        - name: PUBSUB_OUTPUT_TOPIC
          value: output-topic
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/GOOGLE_APPLICATION_CREDENTIALS
        - name: GOOGLE_APPLICATION_CREDENTIALS_JSON
          valueFrom:
            secretKeyRef:
              name: pubsub-secret
              key: GOOGLE_APPLICATION_CREDENTIALS
      #serviceAccountName: worker-sa
